# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

def FibonacciSum(cap)
	sum = 0
	product_array = [1,2]

	
	while product_array[-1] + product_array[-2] <= cap
		sum = product_array[-1] + product_array[-2]
		product_array << sum
	end

	product_array.keep_if{ |number| number.even? }

	product_array.inject("+")
end

puts FibonacciSum(4000000)